### PR TITLE
[#214] Update supported GHC versions

### LINKED ISSUE #214: Update supported GHC versions
1. We do not explicitly support latest GHC (8.6.*), which is bad because we claim to support at least 3 latest versions.
2. GHC-7.10.3 which we explicitly support is rather old and for some reason CI build with GHC-7.10.3 fails. I think it's easier to just drop GHC-7.10.3 support.

So let's update `universum.cabal`,  CI config and maybe something else to drop support of 7.10.3 and add support of 8.6.5.

### PR DESCRIPTION
**Pull request by gromakovsky**
## Description

Problem:
1. We do not explicitly support latest GHC (8.6.*), which is bad
because we claim to support at least 3 latest versions.
2. GHC-7.10.3 which we explicitly support is rather old and for some
reason CI build with GHC-7.10.3 fails. In general it imposes some
maintenance overhead with no big benefit.

Solution:
Support for 7.10.3 is dropped, support for 8.6.5 is added.
1. Update tested GHC versions in .cabal.
2. Update `stack.yaml` files.
3. Add stack.yaml.lock which is a new feature of Stack.
4. Update Travis config.

## Related issues(s)

Fixes #214 

## ✓ Checklist for your Pull Request

- [x] I made sure my PR addresses a single concern, or multiple concerns which
      are inextricably linked. Otherwise I should open multiple PR's.
- [x] If your PR fixes/relates to an open issue then the description should
      reference this issue. See also [auto linking on
      github](https://help.github.com/articles/autolinked-references-and-urls/).

#### Related changes (conditional)

- Tests

  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation

  I checked whether I should update the docs and did so if necessary:

  - [x] [README](/README.md)
  - [x] Haddock

- Record your changes

  - [x] I added an entry to the [changelog](/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commit history is clean (only contains changes relating to my
      issue/pull request and no reverted-my-earlier-commit changes) and commit
      messages start with identifiers of related issues in square brackets.

### CODE REVIEW

**Comment by volhovm** [comment]
So it does compile on nixos now or what? :)

**Comment by gromakovsky** [comment]
I don't know whether it compiles on nixos, but I've fixed `universum-doctest` with newer GHC. If you have any other issues on nixos, let me know.

**Comment by volhovm** [comment]
The current issue is different:

```
Preprocessing test suite 'universum-test' for universum-1.5.0..
Building test suite 'universum-test' for universum-1.5.0..
[1 of 2] Compiling Test.Universum.Property ( test/Test/Universum/Property.hs, dist/build/universum-test/universum-test-tmp/Test/Universum/Property.o )

test/Test/Universum/Property.hs:34:10: error:
    • Couldn't match type ‘Hedgehog.Internal.Gen.GenBase m’
                     with ‘Identity’
        arising from a use of ‘Gen.unicode’
    • In a stmt of a 'do' block: a <- Gen.unicode
      In the expression:
        do a <- Gen.unicode
           if U.elem a ['\65534', ....] then unicode' else return a
      In an equation for ‘unicode'’:
          unicode'
            = do a <- Gen.unicode
                 if U.elem a [...] then unicode' else return a
    • Relevant bindings include
        unicode' :: m Char (bound at test/Test/Universum/Property.hs:33:1)
   |
34 |     a <- Gen.unicode
   |          ^^^^^^^^^^^
```

**Comment by gromakovsky** [comment]
Okay, try again.

**Comment by volhovm** [comment]
I can't just "try again" because it doesn't reproduce on my PC when locally cloned, but instead happens with the revision that is hackage-cloned to nixpkgs.

**Comment by gromakovsky** [comment]
Okay, but can you/did you review the changes from this PR? Is ability to build it on nixos the only thing you want to be added in this PR?

P. S. I've completely reimplemented by last commit.

**Comment by gromakovsky** [comment]
Yes, GitHub won't let me merge it without 2 approvals anyway.

**Comment by gromakovsky** [comment]
If @Martoon-00 wants to make #213 mergeable, he probably should review this PR :wink:

**Comment by Martoon-00** [comment]
> Replace `-qq` with `-q` and remove `--force-yes`, using those is apparently not recommended by manual
Which manual do you refer to? Regarding `-y`, I have seen they advising using it in [Travis tutorial](https://docs.travis-ci.com/user/installing-dependencies/)

**Comment by gromakovsky** [comment]
@Martoon-00 `-y` and `--force-yes` are different flags. I am talking about this manual: https://linux.die.net/man/8/apt-get

```
-q, --quiet
    Quiet. Produces output suitable for logging, omitting progress indicators. More q's will produce more quiet up to a maximum of two. You can also use -q=# to set the quiet level, overriding the configuration file. Note that quiet level 2 implies -y, you should never use -qq without a no-action modifier such as -d, --print-uris or -s as APT may decided to do something you did not expect. 
```

> you should never use -qq without a no-action modifier such as -d, --print-uris or -s as APT may decided to do something you did not expect. 

AFAIU, we don't use such modifiers. And with `-q` the output doesn't seem to be verbose anyway.

```
--force-yes
    Force yes. This is a dangerous option that will cause apt-get to continue without prompting if it is doing something potentially harmful. It should not be used except in very special situations. Using --force-yes can potentially destroy your system! 
```

I think we don't care about possibility of destroying the system (because it's not our own system), but I don't think that our situation is very special and since everything works without this flag I'd rather not use it.

**Pull request merged**
