### PR TITLE
[#185] Enable more warnings and fix them

### LINKED ISSUE #185: Enable -Werror and few more warnings
I think we shouldn't permit warnings, but apparently we do.
Also I'd enable `-Wcompat -Wincomplete-uni-patterns -Wincomplete-record-updates -Wredundant-constraints`. You can read about them [here](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html). They seem to be harmless and helpful.

### PR DESCRIPTION
**Pull request by gromakovsky**
## Description

Here I enable all warnings that I find sane, enable `-Werror` and fix new warnings.

## Related issues(s)

Fixed #185.

## ✓ Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

- [x] I made sure my PR addresses a single concern, or multiple concerns which
      are inextricably linked. Otherwise I should open multiple PR's.
- [x] If your PR fixes/relates to an open issue then the description should
      reference this issue. See also [auto linking on
      github](https://help.github.com/articles/autolinked-references-and-urls/).

#### Related changes (conditional)

- Tests

  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation

  I checked whether I should update the docs and did so if necessary:

  - [x] [README](/README.md)
  - [x] Haddock

- Record your changes

  - [x] I added an entry to the [changelog](/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commit history is clean (only contains changes relating to my
      issue/pull request and no reverted-my-earlier-commit changes) and commit
      messages start with identifiers of related issues in square brackets.

  **Example:** `[#42] Short commit description`

  If necessary both of these can be achieved even after the commits have been
  made/pushed using [rebase and squash](https://git-scm.com/docs/git-rebase).

### CODE REVIEW

**Comment by gromakovsky** [comment]
I can add a `Makefile` which would pass `--ghc-options -Wwarn`. In this case if we switch to another CI we won't accidentally forget to enable `-Werror`.

**Comment by int-index** [comment]
Imagine there's a package `x` which depends on `universum`. How would it disable `-Werror`? Passing `-Wwarn` would only affect `x` itself, and having a Makefile for `universum` would not be helpful at all.

**Comment by gromakovsky** [comment]
Does `--ghc-options -Werror` in `universum.cabal` matter when one builds `x`? I thought no, but if it matters then yes, probably it's better to do it differently.

**Comment by int-index** [comment]
> Does `--ghc-options -Werror` in `universum.cabal` matter when one builds `x`?

Yes. `ghc-options` from the `.cabal` file are in effect if the package is being built as a dependency of another package (why would they be ignored?)

**Comment by gromakovsky** [comment]
Ok, now it's different.

**Pull request merged**
