### PR TITLE
[#152] Use gauge instead of criterion, clean dependencies

### LINKED ISSUE #152: Migrate from 'criterion' to 'gauge'
It's just too hard to build `criterion` each time... I think we can use lighter dependencies.

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #152

### CODE REVIEW

**Comment by vrom911** [comment]
@ChShersh when I was doing benchmarks here I wasn't in the team and didn't know anything about style-guide. But now I see that it differs from the rest of the code. The question is don't you mind me refactoring a bit in here? Or it's better to have it as it is?

**Comment by ChShersh** [comment]
@vrom911 Sure, you can refactor this code if you don't mind!

**Comment by vrom911** [comment]
I though a bit more on refactoring and I see that benefits are not worth it..

**Comment by ChShersh** [comment]
@vrom911 No worries! I will merge then (after CI pass).

**Pull request merged**
